//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlatform.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_ExtraPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buy_ExtraPackage()
        {
            this.Customer_Wishlist = new HashSet<Customer_Wishlist>();
            this.Order_ExtraPackage = new HashSet<Order_ExtraPackage>();
        }
    
        public int OrderID { get; set; }
        public int GameID { get; set; }
        public string ExtraPackageName { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Wishlist> Customer_Wishlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_ExtraPackage> Order_ExtraPackage { get; set; }
        public virtual Registration_Game Registration_Game { get; set; }
    }
}
