//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlatform.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Wishlist
    {
        public int CustomerID { get; set; }
        public Nullable<int> OrderExtraPackageID { get; set; }
        public int OrderGameID { get; set; }
    
        public virtual Buy_ExtraPackage Buy_ExtraPackage { get; set; }
        public virtual Buy_Game Buy_Game { get; set; }
        public virtual Registration_Customer Registration_Customer { get; set; }
    }
}
