//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlatform.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GamePlatformEntities : DbContext
    {
        public GamePlatformEntities()
            : base("name=GamePlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buy_ExtraPackage> Buy_ExtraPackage { get; set; }
        public virtual DbSet<Buy_Game> Buy_Game { get; set; }
        public virtual DbSet<Customer_Wishlist> Customer_Wishlist { get; set; }
        public virtual DbSet<Order_ExtraPackage> Order_ExtraPackage { get; set; }
        public virtual DbSet<Order_Game> Order_Game { get; set; }
        public virtual DbSet<Registration_Company> Registration_Company { get; set; }
        public virtual DbSet<Registration_Coupon> Registration_Coupon { get; set; }
        public virtual DbSet<Registration_Customer> Registration_Customer { get; set; }
        public virtual DbSet<Registration_Game> Registration_Game { get; set; }
        public virtual DbSet<Type_Genres> Type_Genres { get; set; }
        public virtual DbSet<Type_Language> Type_Language { get; set; }
        public virtual DbSet<Type_Package> Type_Package { get; set; }
        public virtual DbSet<Type_Player> Type_Player { get; set; }
    
        public virtual ObjectResult<SP_GetBuyGame_Result> SP_GetBuyGame()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetBuyGame_Result>("SP_GetBuyGame");
        }
    
        public virtual ObjectResult<SP_GetGames_Result> SP_GetGames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetGames_Result>("SP_GetGames");
        }
    }
}
