//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlatform.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_ExtraPackage
    {
        public int PurchaseID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> CouponID { get; set; }
        public int OrderExtraPackageID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string UploadOnDesktop { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Buy_ExtraPackage Buy_ExtraPackage { get; set; }
        public virtual Registration_Coupon Registration_Coupon { get; set; }
        public virtual Registration_Customer Registration_Customer { get; set; }
    }
}
