//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlatform.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration_Game()
        {
            this.Buy_ExtraPackage = new HashSet<Buy_ExtraPackage>();
            this.Buy_Game = new HashSet<Buy_Game>();
            this.Type_Player = new HashSet<Type_Player>();
            this.Type_Genres = new HashSet<Type_Genres>();
            this.Type_Language = new HashSet<Type_Language>();
            this.Type_Language1 = new HashSet<Type_Language>();
        }
    
        public int GameID { get; set; }
        public string GameName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> AgeLimit { get; set; }
        public int DeveloperID { get; set; }
        public int PublisherID { get; set; }
        public string Explanation { get; set; }
        public Nullable<double> AvaragePoint { get; set; }
        public string OprSystem { get; set; }
        public string CPU { get; set; }
        public string Storage { get; set; }
        public string Graphics { get; set; }
        public string Memory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy_ExtraPackage> Buy_ExtraPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy_Game> Buy_Game { get; set; }
        public virtual Registration_Company Registration_Company { get; set; }
        public virtual Registration_Company Registration_Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type_Player> Type_Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type_Genres> Type_Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type_Language> Type_Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type_Language> Type_Language1 { get; set; }
    }
}
