//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlatform.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Player
    {
        public int PlayerTypeID { get; set; }
        public int GameID { get; set; }
        public string Single { get; set; }
        public string Multiplayer { get; set; }
        public string Controller { get; set; }
        public string Co_Op { get; set; }
        public string VR { get; set; }
    
        public virtual Registration_Game Registration_Game { get; set; }
    }
}
